#!/usr/bin/env bash
# a Bash script that generates a MySQL dump and
# creates a compressed archive out of it.

pssword=$1

current_time=$(date +"%d-%m-%Y")
dump_filename="backup.sql"


mysqldump -u "root" -p"$pssword" --all-databases > "$dump_filename"

tar -czvf "${current_time}.tar.gz" "$dump_filename"