#!/usr/bin/env bash
#  Bash script with the minimum number of commands to
# find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80

sudo apt-get install -y nginx
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled
sudo service nginx restart
