#!/usr/bin/env bash
# a script that displays Best School 10 times

n=1
while [ $n -le 20 ]; do
	case $n in
		4)
			echo "$n"
			echo "bad luck from China";;
		9)
			echo "$n"
			echo "bad luck from Japan";;
		17)
			echo "$n"
			echo "bad luck from Italy";;
		*)
			echo "$n";;
	esac
	((n++))
done
