#!/usr/bin/env bash
# a script that displays Best School 10 times using while

n=0
while [ "$n" -le 12 ]; do
	echo "Hour: $n"
	m=1
	while [ "$m" -le 59 ]; do
		echo "$m"
		((m++))
	done
	((n++))
done
