#!/usr/bin/env bash
# Ascript that configures firewall to block all incoming traffic
sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw disable
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp